# --- Game Configuration ---
POSE_HOLD_TIME = 2.0
SESSION_COOLDOWN = 3
FEEDBACK_DISPLAY_DURATION = 2.0
TARGET_RADIUS = 20
MATCH_THRESHOLD = 40
TARGETS_PER_CYCLE = 4
TARGET_CYCLES = 3
CYCLE_TIME_LIMIT = 30

# --- Yoga Mode ---
YOGA_POSE_IMAGES = [
    'yoga_poses/goddess.jpg',
    'yoga_poses/high-lunge.jpg',
    'yoga_poses/post-big-image.jpg',
    'yoga_poses/31-warrior-2.jpg',
    'yoga_poses/side-bend.jpg'
]
YOGA_SIMILARITY_THRESHOLD = 0.95
YOGA_CYCLE_TIME_LIMIT = 30
YOGA_POSE_HOLD_DURATION = 1.0

# --- Rhythm Mode ---
RHYTHM_SEQUENCE_LENGTH = 10
RHYTHM_TARGET_TIME_LIMIT = 3.0

# --- Dodger Mode ---
DODGER_INITIAL_LIVES = 3
DODGER_SPAWN_RATE = 0.5
DODGER_GOOD_ITEM_CHANCE = 0.6
DODGER_POINTS_PER_ITEM = 50
DODGER_MAGNET_RANGE = 200
DODGER_MAGNET_STRENGTH = 0.1

# --- Ninja Slicer Mode ---
NINJA_SLICER_INITIAL_LIVES = 3
NINJA_SLICER_SPAWN_RATE = 0.8
NINJA_SLICER_FRUIT_CHANCE = 0.8
NINJA_SLICER_POINTS_PER_FRUIT = 10
TRAIL_LENGTH = 10
